[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc", "rust-analyzer", "clippy", "rust-src", "rust-std" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "x86_64-apple-darwin" ]
profile = "default"
